export interface ThreatItem {
  component: string;
  threat: string;
  likelihood: string;
  impact: string;
  mitigation: string;
  codeEvidence: string;
  strideCategory: string;
  dreadScore: number;
  owaspCategory: string;
  mitreAttackTactic?: string;        // e.g. "Initial Access"
  mitreAttackTechnique?: string;     // e.g. "Exploit Public-Facing Application"
  mitreAttackTechniqueId?: string;   // e.g. "T1190"
}

export interface QuestionnaireItem {
  id: number;
  question: string;
  answer: string;
  evidence: string;
  confidence: 'Confirmed' | 'Inferred' | 'Needs Manual Verification';
}

export interface CveFinding {
  packageName: string;
  version: string;
  ecosystem: string;
  vulnId: string;
  summary: string;
  severity: string;
  fixedVersion: string | null;
  reachable?: boolean | null;
}

export interface SecretFinding {
  path: string;
  line: number;
  type: string;
  preview: string;
}

export interface SbomComponent {
  name: string;
  version: string;
  ecosystem: string;
  purl: string;
}

export interface ApiEndpoint {
  endpoint: string;
  mutating: boolean;
  authn: string;
  authz: string;
  externalFacing: boolean;
}

export interface ApiGatewayChecklist {
  https: boolean;
  approvedAuth: boolean;
  rateLimiting: boolean;
  anomalyMonitoring: boolean;
  notes: string;
}

export interface MonitoringInfo {
  loggingFramework: string;
  logDestination: string;
  retentionPolicy: string;
  alertingSetup: string;
}

export interface IacFinding {
  resource: string;
  check: string;
  severity: 'Critical' | 'High' | 'Medium' | 'Low';
  file: string;
  line?: number;
  framework: string;
}

export interface OwaspAsvs {
  chapter: string;
  requirement: string;
  level: 1 | 2 | 3;
  status: 'pass' | 'fail' | 'not-applicable';
  evidence: string;
}

export interface ComplianceGap {
  framework: string;
  control: string;
  status: 'pass' | 'fail' | 'partial';
  notes: string;
}

export interface PentestScope {
  highRiskAreas: string[];
  attackSurface: string[];
  testingRecommendations: string[];
  estimatedEffort: string;
}

export interface FairRiskEstimate {
  threat: string;
  annualLossExpectancy: string;
  riskBand: 'low' | 'medium' | 'high' | 'critical';
  assumptions: string;
}

export interface LicenseFinding {
  packageName: string;
  version: string;
  spdxLicense: string;
  riskCategory: 'Permissive' | 'Weak Copyleft' | 'Strong Copyleft' | 'Unknown';
  requiresReview: boolean;
}

export interface SupplyChainRisk {
  packageName: string;
  signals: string[];
  riskLevel: 'low' | 'medium' | 'high';
}

export interface SemgrepFinding {
  rule: string;
  severity: string;
  description: string;
  file: string;
  line: number;
  cweId?: string;
}

export interface AnalysisResult {
  riskCategory: string;
  riskReasoning: string;
  mermaidDiagram: string;
  threats: ThreatItem[];
  questionnaire: QuestionnaireItem[];
  irpDraft: string;
  thinkingText: string;
  securityScore: number;
  cveScanResults: CveFinding[];
  secretScanFindings: SecretFinding[];
  sbom: SbomComponent[];

  // GoDaddy template fields
  inScope: string[];
  outOfScope: string[];
  architecturalAssumptions: string[];
  dataFlowDiagram: string;          // Mermaid flowchart (separate from architecture diagram)
  apiInventory: ApiEndpoint[];
  apiGatewayChecklist: ApiGatewayChecklist;
  secretsAndCredentials: string;
  monitoringAndLogging: MonitoringInfo;
  gitSha: string;

  // Industry-standard enrichment (generated by Claude)
  iacFindings: IacFinding[];
  slsaLevel: 0 | 1 | 2 | 3;
  slsaReasoning: string;
  owaspAsvs: OwaspAsvs[];
  complianceGaps: ComplianceGap[];
  pentestScope: PentestScope;
  fairRiskEstimates: FairRiskEstimate[];

  // Enriched later (not from Claude)
  epssScores: Record<string, number>;
  licenseFindings: LicenseFinding[];
  supplyChainRisks: SupplyChainRisk[];
  semgrepFindings: SemgrepFinding[];
}
