import type { AnalysisResult } from '../lib/analyzer.js';

function authHeader() {
  const email = process.env.ATLASSIAN_EMAIL!;
  const token = process.env.ATLASSIAN_API_TOKEN!;
  return 'Basic ' + Buffer.from(`${email}:${token}`).toString('base64');
}

const BASE = process.env.ATLASSIAN_BASE_URL ?? 'https://godaddy-corp.atlassian.net';

// ─── Confluence (v1 REST API) ─────────────────────────────────────────────────

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function resultToHtml(result: AnalysisResult, repoUrl: string): string {
  const e = (s: unknown) => escapeHtml(String(s ?? ''));
  const repoName = repoUrl.split('/').pop() ?? repoUrl;

  const threatRows = (result.threats ?? [])
    .map((t) =>
      `<tr><td>${e(t.component)}</td><td>${e(t.threat)}</td><td>${e(t.likelihood)}</td><td>${e(t.impact)}</td><td>${e(t.mitigation)}</td><td><code>${e(t.codeEvidence)}</code></td></tr>`
    )
    .join('');

  const qaRows = (result.questionnaire ?? [])
    .map((q) =>
      `<tr><td>${q.id}</td><td>${e(q.question)}</td><td>${e(q.answer)}</td><td><code>${e(q.evidence)}</code></td></tr>`
    )
    .join('');

  let cveSection = '';
  if (result.cveScanResults && result.cveScanResults.length > 0) {
    const critHighCves = result.cveScanResults.filter(c =>
      c.severity === 'Critical' || c.severity === 'High'
    );
    const cveRows = result.cveScanResults
      .slice(0, 20)
      .map(c =>
        `<tr><td>${e(c.packageName)}@${e(c.version)}</td><td>${e(c.vulnId)}</td><td>${e(c.severity)}</td><td>${e((c.summary ?? '').slice(0, 80))}</td><td>${e(c.fixedVersion ?? 'No patch available')}</td></tr>`
      )
      .join('');
    cveSection = `<hr/><h2>Dependency CVEs (${result.cveScanResults.length} total, ${critHighCves.length} critical/high)</h2>
<table><tr><th>Package</th><th>CVE ID</th><th>Severity</th><th>Summary</th><th>Fix</th></tr>${cveRows}</table>`;
  }

  let secretSection = '';
  if (result.secretScanFindings && result.secretScanFindings.length > 0) {
    const items = result.secretScanFindings
      .map(s => `<li><strong>${e(s.type)}</strong> at <code>${e(s.path)}:${s.line}</code> (${e(s.preview)})</li>`)
      .join('');
    secretSection = `<hr/><h2>Potential Secrets Detected</h2><ul>${items}</ul>`;
  }

  const irpLines = String(result.irpDraft ?? 'No IRP generated')
    .split('\n')
    .map(line => `<p>${e(line)}</p>`)
    .join('\n');

  return `<h1>Security Certification Package — ${e(repoName)}</h1>
<p><strong>Repo:</strong> ${e(repoUrl)}<br/>
<strong>Generated:</strong> ${new Date().toISOString().split('T')[0]}<br/>
<strong>Risk Category:</strong> ${e(result.riskCategory)}<br/>
<strong>Security Score:</strong> ${result.securityScore ?? 'N/A'}/100</p>
<hr/>
<h2>Risk Assessment</h2>
<p>${e(result.riskReasoning)}</p>
<hr/>
<h2>Architecture Diagram</h2>
<pre>${e(result.mermaidDiagram)}</pre>
<hr/>
<h2>Threat Model</h2>
<table><tr><th>Component</th><th>Threat</th><th>Likelihood</th><th>Impact</th><th>Mitigation</th><th>Evidence</th></tr>${threatRows}</table>
<hr/>
<h2>Security Questionnaire (${(result.questionnaire ?? []).length}/29)</h2>
<table><tr><th>#</th><th>Question</th><th>Answer</th><th>Evidence</th></tr>${qaRows}</table>
<hr/>
<h2>Incident Response Plan (Draft)</h2>
${irpLines}
<hr/>
<p><em>Generated by CertAI — Hackathon 2026</em></p>${cveSection}${secretSection}`;
}

export async function publishToConfluence(
  spaceKey: string,
  repoUrl: string,
  result: AnalysisResult
): Promise<{ pageId: string; pageUrl: string }> {
  const title = `[CertAI] ${repoUrl.split('/').pop()} — ${new Date().toISOString().split('T')[0]}`;
  const htmlBody = resultToHtml(result, repoUrl);

  const res = await fetch(`${BASE}/wiki/rest/api/content`, {
    method: 'POST',
    headers: {
      Authorization: authHeader(),
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: JSON.stringify({
      type: 'page',
      title,
      space: { key: spaceKey },
      body: {
        storage: {
          value: htmlBody,
          representation: 'storage',
        },
      },
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Confluence create failed: ${res.status} ${text}`);
  }

  const page = await res.json();
  const webui = page._links?.webui ?? `/spaces/${spaceKey}/pages/${page.id}`;
  return {
    pageId: page.id,
    pageUrl: `${BASE}/wiki${webui}`,
  };
}

// ─── Jira ─────────────────────────────────────────────────────────────────────

export async function createJiraTicket(
  repoUrl: string,
  result: AnalysisResult,
  confluenceUrl: string
): Promise<{ ticketKey: string; ticketUrl: string }> {
  const projectKey = process.env.JIRA_PROJECT_KEY ?? 'SECARCH';

  const res = await fetch(`${BASE}/rest/api/3/issue`, {
    method: 'POST',
    headers: {
      Authorization: authHeader(),
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: JSON.stringify({
      fields: {
        project: { key: projectKey },
        summary: `[CertAI] Security cert package — ${repoUrl.split('/').pop()}`,
        issuetype: { name: 'Task' },
        description: {
          type: 'doc',
          version: 1,
          content: [
            {
              type: 'paragraph',
              content: [
                {
                  type: 'text',
                  text: `CertAI generated security certification package for ${repoUrl}. Risk: ${result.riskCategory}. Full report: ${confluenceUrl}`,
                },
              ],
            },
          ],
        },
      },
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Jira create failed: ${res.status} ${text}`);
  }

  const issue = await res.json();
  return {
    ticketKey: issue.key,
    ticketUrl: `${BASE}/browse/${issue.key}`,
  };
}
