import type { AnalysisResult } from '../lib/analyzer.js';

function authHeader() {
  const email = process.env.ATLASSIAN_EMAIL!;
  const token = process.env.ATLASSIAN_API_TOKEN!;
  return 'Basic ' + Buffer.from(`${email}:${token}`).toString('base64');
}

const BASE = process.env.ATLASSIAN_BASE_URL ?? 'https://godaddy-corp.atlassian.net';

// ─── Confluence ───────────────────────────────────────────────────────────────

export async function getSpaceId(spaceKey: string): Promise<string> {
  const res = await fetch(
    `${BASE}/wiki/api/v2/spaces?keys=${spaceKey}&limit=1`,
    { headers: { Authorization: authHeader(), Accept: 'application/json' } }
  );
  const data = await res.json();
  const space = data.results?.[0];
  if (!space) throw new Error(`Space not found: ${spaceKey}`);
  return space.id;
}

export function resultToMarkdown(result: AnalysisResult, repoUrl: string): string {
  const threats = result.threats
    .map(
      (t) =>
        `| ${t.component} | ${t.threat} | ${t.likelihood} | ${t.impact} | ${t.mitigation} | \`${t.codeEvidence}\` |`
    )
    .join('\n');

  const qa = result.questionnaire
    .map((q) => `| ${q.id} | ${q.question} | ${q.answer} | \`${q.evidence}\` |`)
    .join('\n');

  return `# Security Certification Package — ${repoUrl.split('/').pop()}

**Repo:** ${repoUrl}
**Generated:** ${new Date().toISOString().split('T')[0]}
**Risk Category:** ${result.riskCategory}

---

## Risk Assessment

${result.riskReasoning}

---

## Architecture Diagram

\`\`\`mermaid
${result.mermaidDiagram}
\`\`\`

---

## Threat Model

| Component | Threat | Likelihood | Impact | Mitigation | Evidence |
|-----------|--------|-----------|--------|------------|---------|
${threats}

---

## Security Questionnaire (${result.questionnaire.length}/29)

| # | Question | Answer | Evidence |
|---|----------|--------|---------|
${qa}

---

## Incident Response Plan (Draft)

${result.irpDraft}

---
*Generated by CertAI — Hackathon 2026*`;
}

export async function publishToConfluence(
  spaceKey: string,
  repoUrl: string,
  result: AnalysisResult
): Promise<{ pageId: string; pageUrl: string }> {
  const spaceId = await getSpaceId(spaceKey);
  const title = `[CertAI] ${repoUrl.split('/').pop()} — ${new Date().toISOString().split('T')[0]}`;
  const body = resultToMarkdown(result, repoUrl);

  const res = await fetch(`${BASE}/wiki/api/v2/pages`, {
    method: 'POST',
    headers: {
      Authorization: authHeader(),
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: JSON.stringify({
      spaceId,
      title,
      body: { representation: 'wiki', value: body },
      status: 'current',
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Confluence create failed: ${res.status} ${text}`);
  }

  const page = await res.json();
  return {
    pageId: page.id,
    pageUrl: `${BASE}/wiki/spaces/${spaceKey}/pages/${page.id}`,
  };
}

// ─── Jira ─────────────────────────────────────────────────────────────────────

export async function createJiraTicket(
  repoUrl: string,
  result: AnalysisResult,
  confluenceUrl: string
): Promise<{ ticketKey: string; ticketUrl: string }> {
  const projectKey = process.env.JIRA_PROJECT_KEY ?? 'SECARCH';

  const res = await fetch(`${BASE}/rest/api/3/issue`, {
    method: 'POST',
    headers: {
      Authorization: authHeader(),
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: JSON.stringify({
      fields: {
        project: { key: projectKey },
        summary: `[CertAI] Security cert package — ${repoUrl.split('/').pop()}`,
        issuetype: { name: 'Task' },
        description: {
          type: 'doc',
          version: 1,
          content: [
            {
              type: 'paragraph',
              content: [
                {
                  type: 'text',
                  text: `CertAI generated security certification package for ${repoUrl}. Risk: ${result.riskCategory}. Full report: ${confluenceUrl}`,
                },
              ],
            },
          ],
        },
      },
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Jira create failed: ${res.status} ${text}`);
  }

  const issue = await res.json();
  return {
    ticketKey: issue.key,
    ticketUrl: `${BASE}/browse/${issue.key}`,
  };
}
